version: 2.1
orbs:
  docker: circleci/docker@1.0.0
  heroku: circleci/heroku@1.2.2
workflows:
  deploy:
    jobs:
      - docker/publish:
          image: dareedyone/dwdthreepointtwo
          tag: "latest"
  heroku_deploy:
    jobs:
      - push-docker-image:
          requires:
            - docker/publish
          app_name: $HEROKU_APP_NAME
          api-key: $HEROKU_API_KEY
